name: dependence_file_annotation
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
